DROP DATABASE IF EXISTS gList;
CREATE DATABASE gList;

USE gList;

CREATE TABLE groceryList (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  quantity INT NOT NULL,
  PRIMARY KEY(id)
)